name: Flight Booking CICD

on:
  push:
    branches:
      - dev
      - main

jobs:
  upload-to-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest 
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/1061956692764/locations/global/workloadIdentityPools/nsk-github-pool/providers/github-provider'
          service_account: '1061956692764-compute@developer.gserviceaccount.com'
          project_id: 'project-0bc8a567-62b7-4045-a22'
        #with:
        #  credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Upload `variables.json` to Composer bucket
      - name: Upload Variables JSON to GCS
        run: |
          gsutil cp flight_booking_data_pipeline/variables/dev/variables.json gs://us-central1-airflow-test-1-1c727776-bucket/data/dev/variables.json
      # Import Variables into Airflow-DEV
      - name: Import Variables into Airflow-test-1
        run: |
          gcloud composer environments run airflow-test-1 \
            --location us-central1 \
            variables import -- /home/airflow/gcs/data/dev/variables.json

      # Sync Spark job to GCS
      - name: Upload Spark Job to GCS
        run: |
          gsutil cp flight_booking_data_pipeline/spark_job/spark_transformation_job.py gs://nsk-airflow-projects-gds-dev/flight-booking-analysis/spark-job/


      # Sync Airflow DAG to Airflow DEV Composer
      - name: Upload Airflow DAG to DEV Environment (Dag Folder)
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-test-1 \
            --location us-central1 \
            --source flight_booking_data_pipeline/airflow_job/airflow_job.py

  upload-to-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to GCP Account
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/1061956692764/locations/global/workloadIdentityPools/nsk-github-pool/providers/github-provider'
          service_account: '1061956692764-compute@developer.gserviceaccount.com'
          project_id: 'project-0bc8a567-62b7-4045-a22'
        #with:
        #  credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Upload `variables.json` to Composer bucket
      - name: Upload Variables JSON to GCS
        run: |
          gsutil cp flight_booking_data_pipeline/variables/prod/variables.json gs://us-central1-airflow-test-1-1c727776-bucket/data/prod/variables.json

      # Import Variables into Airflow-PROD
      - name: Import Variables into airflow-test-1
        run: |
          gcloud composer environments run airflow-test-1 \
            --location us-central1 \
            variables import -- /home/airflow/gcs/data/prod/variables.json

      # Sync Spark job to GCS
      - name: Upload Spark Job to GCS
        run: |
          gsutil cp flight_booking_data_pipeline/spark_job/spark_transformation_job.py gs://nsk-airflow-projects-gds-dev/flight-booking-analysis/spark-job/

      # Sync Airflow DAG to Airflow PROD Composer
      - name: Upload Airflow DAG to PROD Environment (Dag Folder)
        run: |
          gcloud composer environments storage dags import \
            --environment airflow-test-1 \
            --location us-central1 \
            --source flight_booking_data_pipeline/airflow_job/airflow_job.py
